apiVersion: multik8s.platformref.crossplane.io/v1alpha1
kind: Network
metadata:
  name: crossplane-poc-network
spec:
  id: crossplane-poc-network
  clusterRef:
    id: crossplane-poc-k8s
  compositionSelector:
    matchLabels:
      provider: GCP
