apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    secretRef:
      key: key 
      name: gcp-credentials
      namespace: crossplane-system
    source: Secret
  projectID: flash-hour-354609
